<?php
require 'login_check.php'; include 'db.php'; include 'config.php';
if (!isset($_SESSION['business_account_id'])) craftcrawl_redirect('business_login.php');
$claim_id = filter_var($_GET['claim_id'] ?? null, FILTER_VALIDATE_INT); $account_id=(int)$_SESSION['business_account_id'];
$stmt=$conn->prepare("SELECT bc.*, l.name FROM business_claims bc INNER JOIN locations l ON l.id=bc.location_id WHERE bc.id=? AND bc.requester_account_id=? LIMIT 1");
$stmt->bind_param('ii',$claim_id,$account_id); $stmt->execute(); $claim=$stmt->get_result()->fetch_assoc(); if(!$claim) craftcrawl_redirect('business/locations.php');
if($_SERVER['REQUEST_METHOD']==='POST' && $claim['status']==='needs_more_info'){ craftcrawl_verify_csrf(); $notes=trim(strip_tags($_POST['verification_notes']??'')); $u=$conn->prepare("UPDATE business_claims SET verification_notes=?, status='pending', updatedAt=NOW() WHERE id=?"); $u->bind_param('si',$notes,$claim_id); $u->execute(); craftcrawl_redirect('business_claim_status.php?claim_id='.$claim_id);}
?>
<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, viewport-fit=cover"><title>Claim Status</title><script src="js/theme_init.js?v=<?php echo filemtime(__DIR__.'/js/theme_init.js'); ?>"></script><link rel="stylesheet" href="css/style.css?v=<?php echo filemtime(__DIR__.'/css/style.css'); ?>"><?php require_once __DIR__ . '/lib/google_analytics.php'; echo craftcrawl_google_analytics_tag(); ?></head><body class="auth-body"><main class="auth-card auth-card-wide"><h1><?php echo escape_output($claim['name']); ?></h1><p>Status: <strong><?php echo escape_output(ucwords(str_replace('_',' ',$claim['status']))); ?></strong></p><?php if(!empty($claim['adminNotes'])):?><p><?php echo nl2br(escape_output($claim['adminNotes'])); ?></p><?php endif;?><?php if($claim['status']==='needs_more_info'):?><form method="POST"><?php echo craftcrawl_csrf_input(); ?><label>Add requested information</label><textarea name="verification_notes" rows="5"><?php echo escape_output($claim['verification_notes']); ?></textarea><button type="submit">Resubmit</button></form><?php endif;?><p><a href="business/locations.php">Back to locations</a></p></main></body></html>
