<?php
require 'login_check.php'; include 'db.php'; include 'config.php'; require_once 'lib/location_duplicates.php';
if(!isset($_SESSION['user_id'])) craftcrawl_redirect('user_login.php');
$message=null; $user_id=(int)$_SESSION['user_id'];
function clean_text($v){return trim(strip_tags($v??''));}
if($_SERVER['REQUEST_METHOD']==='POST'){
 craftcrawl_verify_csrf();
 $name=clean_text($_POST['suggested_name']??''); $type=clean_text($_POST['suggested_type']??''); $place=clean_text($_POST['mapbox_place_id']??'');
 $address=clean_text($_POST['address_address-search']??$_POST['address']??''); $apt=clean_text($_POST['apt_suite']??''); $city=clean_text($_POST['city']??''); $state=strtoupper(clean_text($_POST['state']??'')); $zip=clean_text($_POST['zip']??'');
 $lat=filter_var($_POST['latitude']??null,FILTER_VALIDATE_FLOAT); $lng=filter_var($_POST['longitude']??null,FILTER_VALIDATE_FLOAT); $phone=clean_text($_POST['phone']??''); $website=filter_var(trim($_POST['website']??''),FILTER_SANITIZE_URL); $notes=clean_text($_POST['user_notes']??'');
 if($name===''||$type===''||$place===''||$address===''||$city===''||$state===''||$lat===false||$lng===false){
  $missing=[];
  if($name==='')$missing[]='name'; if($type==='')$missing[]='type'; if($place==='')$missing[]='Mapbox selection ID'; if($address==='')$missing[]='street address'; if($city==='')$missing[]='city'; if($state==='')$missing[]='state'; if($lat===false||$lng===false)$missing[]='coordinates';
  $message='Please choose an exact Mapbox address and complete the required fields. Missing: '.implode(', ',$missing).'.';
 }
 else { $s=$conn->prepare("INSERT INTO location_suggestions (suggested_by_user_id,suggested_name,suggested_type,mapbox_place_id,street_address,apt_suite,city,state,zip,latitude,longitude,phone,website,user_notes,createdAt) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,NOW())"); $s->bind_param('issssssssddsss',$user_id,$name,$type,$place,$address,$apt,$city,$state,$zip,$lat,$lng,$phone,$website,$notes); $s->execute(); craftcrawl_redirect('user/portal.php?message=suggestion_saved'); }
}
?>
<!doctype html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Suggest Location</title><script>window.MAPBOX_ACCESS_TOKEN=<?php echo json_encode($MAPBOX_ACCESS_TOKEN); ?>;</script><script id="search-js" defer src="https://api.mapbox.com/search-js/v1.5.0/web.js"></script><link rel="stylesheet" href="css/style.css?v=<?php echo filemtime(__DIR__.'/css/style.css');?>"></head><body class="auth-body"><main class="auth-card auth-card-wide"><a href="user/portal.php">Back</a><h1>Suggest a Location</h1><?php if($message):?><p class="form-message form-message-error"><?php echo escape_output($message);?></p><?php endif;?><form method="POST"><?php echo craftcrawl_csrf_input();?><label for="suggested_name">Name</label><input id="suggested_name" name="suggested_name" required><label for="suggested_type">Type</label><select id="suggested_type" name="suggested_type" required><option value="brewery">Brewery</option><option value="winery">Winery</option><option value="cidery">Cidery</option><option value="distillery">Distillery</option><option value="meadery">Meadery</option></select><label for="street_address">Street Address</label><input id="street_address" name="address" required autocomplete="address-line1"><p class="form-help">Start typing a street address and select an exact Mapbox result.</p><label for="apt_suite">Apartment / Suite</label><input id="apt_suite" name="apt_suite"><div class="business-form-row business-form-row-address"><div><label for="city">City</label><input id="city" name="city" readonly required></div><div><label for="state">State</label><input id="state" name="state" readonly required></div><div><label for="zip">ZIP</label><input id="zip" name="zip" readonly></div></div><input id="latitude" name="latitude" type="hidden"><input id="longitude" name="longitude" type="hidden"><input id="mapbox_place_id" name="mapbox_place_id" type="hidden"><label for="phone">Phone</label><input id="phone" name="phone"><label for="website">Website</label><input id="website" name="website" type="url"><label for="user_notes">Notes</label><textarea id="user_notes" name="user_notes"></textarea><button type="submit">Submit Suggestion</button></form></main><script src="js/location_suggestion.js?v=<?php echo time();?>"></script></body></html>
