CREATE TABLE IF NOT EXISTS location_import_operations (
    operation_id VARCHAR(40) PRIMARY KEY,
    source_provider ENUM('google') NOT NULL DEFAULT 'google',
    state CHAR(2) NOT NULL,
    limit_tiles INT NOT NULL DEFAULT 0,
    dry_run BOOL NOT NULL DEFAULT TRUE,
    total_tiles INT NOT NULL DEFAULT 0,
    total_searches INT NOT NULL DEFAULT 0,
    total_steps INT NOT NULL DEFAULT 0,
    completed_steps INT NOT NULL DEFAULT 0,
    current_tile_label VARCHAR(100),
    current_search_term VARCHAR(100),
    status ENUM('queued', 'running', 'completed', 'failed') NOT NULL DEFAULT 'queued',
    raw_result_count INT NOT NULL DEFAULT 0,
    created_count INT NOT NULL DEFAULT 0,
    review_count INT NOT NULL DEFAULT 0,
    rejected_count INT NOT NULL DEFAULT 0,
    duplicate_count INT NOT NULL DEFAULT 0,
    skipped_count INT NOT NULL DEFAULT 0,
    error_count INT NOT NULL DEFAULT 0,
    api_error TEXT,
    startedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME,
    completedAt DATETIME,
    KEY idx_location_import_operations_status (status),
    KEY idx_location_import_operations_started (startedAt)
);
