<?php
require_once __DIR__.'/../lib/admin_auth.php'; require_once __DIR__.'/../lib/location_hours.php'; require_once __DIR__.'/../lib/admin_review.php'; craftcrawl_require_admin(); include '../db.php';
$id=filter_var($_GET['id']??null,FILTER_VALIDATE_INT); if(!$id) craftcrawl_redirect('admin/dashboard.php');
$stmt=$conn->prepare("SELECT id,name FROM locations WHERE id=?");$stmt->bind_param('i',$id);$stmt->execute();$location=$stmt->get_result()->fetch_assoc(); if(!$location)craftcrawl_redirect('admin/dashboard.php');
$hours=craftcrawl_location_hours_for_form($conn,$id); $message=null;
$return_to = trim($_GET['return_to'] ?? $_POST['return_to'] ?? '');
$allowed_returns = ['readiness' => 'readiness.php', 'reports' => 'reports.php', 'location_detail' => 'location_detail.php?id=' . $id, 'recovery' => 'recovery.php'];
$redirect_target = isset($allowed_returns[$return_to]) ? 'admin/' . $allowed_returns[$return_to] : 'admin/location_detail.php?id=' . $id;
if($_SERVER['REQUEST_METHOD']==='POST'){craftcrawl_verify_csrf();$hours=craftcrawl_business_hours_from_post($_POST);$err=craftcrawl_validate_business_hours($hours);if($err){$message=$err;}else{$conn->begin_transaction();craftcrawl_save_location_hours($conn,$id,$hours,'admin_manual');$u=$conn->prepare("UPDATE location_hours SET verifiedAt=NOW(),verifiedByAdminId=? WHERE location_id=?");$u->bind_param('ii',$_SESSION['admin_id'],$id);$u->execute();craftcrawl_log_admin_review_action($conn,(int)$_SESSION['admin_id'],'location',$id,'approved','Hours verified');$conn->commit();craftcrawl_redirect($redirect_target . (strpos($redirect_target, '?') !== false ? '&' : '?') . 'message=hours_saved');}}
$admin_page_title = craftcrawl_admin_escape($location['name']) . ' Hours';
$admin_page_subtitle = 'Edit and verify business hours.';
$admin_page_extra_scripts = ['../js/business_hours_editor.js'];
include __DIR__ . '/admin_header.php';
?>
        <a href="<?php echo craftcrawl_admin_escape(isset($allowed_returns[$return_to]) ? $allowed_returns[$return_to] : 'location_detail.php?id=' . $id); ?>">Back</a><?php if($message):?><p class="form-message form-message-error"><?php echo craftcrawl_admin_escape($message);?></p><?php endif;?><form method="POST"><?php echo craftcrawl_csrf_input();?><fieldset class="business-hours-editor"><legend>Location Hours</legend><p class="form-help">For late-night hours, choose the opening day and set the close time after midnight. Example: Friday 4:00 PM to 2:00 AM means check-ins stay available until Saturday 2:00 AM.</p><div class="business-hours-bulk" data-business-hours-bulk><div class="business-hours-bulk-times"><label>Opens<input type="time" data-hours-template-open></label><label>Closes<input type="time" data-hours-template-close></label><label class="business-hours-bulk-closed"><input type="checkbox" data-hours-template-closed>Closed</label></div><div class="business-hours-bulk-days" aria-label="Days to update"><?php foreach($hours as $day=>$h):?><label><input type="checkbox" value="<?php echo craftcrawl_admin_escape($day);?>" data-hours-target-day><?php echo craftcrawl_admin_escape(substr($h['day_label'],0,3));?></label><?php endforeach;?></div><div class="business-hours-bulk-actions"><button type="button" data-hours-select="weekdays">Weekdays</button><button type="button" data-hours-select="weekend">Weekend</button><button type="button" data-hours-select="all">All Days</button><button type="button" data-hours-select="clear">Clear</button><button type="button" data-hours-apply>Apply to Selected</button></div></div><?php foreach($hours as $day=>$h):?><div class="business-hours-row" data-hours-row="<?php echo craftcrawl_admin_escape($day);?>"><span><?php echo craftcrawl_admin_escape($h['day_label']);?></span><label><input type="checkbox" name="hours_closed[<?php echo craftcrawl_admin_escape($day);?>]" value="1" data-hours-closed <?php echo $h['is_closed']?'checked':'';?>>Closed</label><label>Opens<input type="time" name="hours_open[<?php echo craftcrawl_admin_escape($day);?>]" value="<?php echo craftcrawl_admin_escape($h['opens_at']);?>" data-hours-open></label><label>Closes<input type="time" name="hours_close[<?php echo craftcrawl_admin_escape($day);?>]" value="<?php echo craftcrawl_admin_escape($h['closes_at']);?>" data-hours-close></label></div><?php endforeach;?></fieldset><button>Save verified hours</button></form>
<?php include __DIR__ . '/admin_footer.php'; ?>
