<?php
require_once __DIR__.'/../lib/admin_auth.php'; require_once __DIR__.'/../lib/location_hours.php'; require_once __DIR__.'/../lib/admin_review.php'; craftcrawl_require_admin(); include '../db.php';
$id=filter_var($_GET['id']??null,FILTER_VALIDATE_INT); if(!$id) craftcrawl_redirect('admin/review_center.php');
$stmt=$conn->prepare("SELECT id,name FROM locations WHERE id=?");$stmt->bind_param('i',$id);$stmt->execute();$location=$stmt->get_result()->fetch_assoc(); if(!$location)craftcrawl_redirect('admin/review_center.php');
$hours=craftcrawl_location_hours_for_form($conn,$id); $message=null;
if($_SERVER['REQUEST_METHOD']==='POST'){craftcrawl_verify_csrf();$hours=craftcrawl_business_hours_from_post($_POST);$err=craftcrawl_validate_business_hours($hours);if($err){$message=$err;}else{$conn->begin_transaction();craftcrawl_save_location_hours($conn,$id,$hours,'admin_manual');$u=$conn->prepare("UPDATE location_hours SET verifiedAt=NOW(),verifiedByAdminId=? WHERE location_id=?");$u->bind_param('ii',$_SESSION['admin_id'],$id);$u->execute();craftcrawl_log_admin_review_action($conn,(int)$_SESSION['admin_id'],'location',$id,'approved','Hours verified');$conn->commit();craftcrawl_redirect('admin/review_center.php?message=hours_saved');}}
?>
<!doctype html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Edit Location Hours</title><link rel="stylesheet" href="../css/style.css?v=<?php echo filemtime(__DIR__.'/../css/style.css');?>"><?php require_once dirname(__DIR__) . '/lib/google_analytics.php'; echo craftcrawl_google_analytics_tag(); ?></head><body><div data-area-page-content><main class="business-portal admin-page"><a href="review_center.php">Back</a><h1><?php echo craftcrawl_admin_escape($location['name']);?> Hours</h1><?php if($message):?><p class="form-message form-message-error"><?php echo craftcrawl_admin_escape($message);?></p><?php endif;?><form method="POST"><?php echo craftcrawl_csrf_input();?><fieldset class="business-hours-editor"><legend>Location Hours</legend><p class="form-help">For late-night hours, choose the opening day and set the close time after midnight. Example: Friday 4:00 PM to 2:00 AM means check-ins stay available until Saturday 2:00 AM.</p><div class="business-hours-bulk" data-business-hours-bulk><div class="business-hours-bulk-times"><label>Opens<input type="time" data-hours-template-open></label><label>Closes<input type="time" data-hours-template-close></label><label class="business-hours-bulk-closed"><input type="checkbox" data-hours-template-closed>Closed</label></div><div class="business-hours-bulk-days" aria-label="Days to update"><?php foreach($hours as $day=>$h):?><label><input type="checkbox" value="<?php echo craftcrawl_admin_escape($day);?>" data-hours-target-day><?php echo craftcrawl_admin_escape(substr($h['day_label'],0,3));?></label><?php endforeach;?></div><div class="business-hours-bulk-actions"><button type="button" data-hours-select="weekdays">Weekdays</button><button type="button" data-hours-select="weekend">Weekend</button><button type="button" data-hours-select="all">All Days</button><button type="button" data-hours-select="clear">Clear</button><button type="button" data-hours-apply>Apply to Selected</button></div></div><?php foreach($hours as $day=>$h):?><div class="business-hours-row" data-hours-row="<?php echo craftcrawl_admin_escape($day);?>"><span><?php echo craftcrawl_admin_escape($h['day_label']);?></span><label><input type="checkbox" name="hours_closed[<?php echo craftcrawl_admin_escape($day);?>]" value="1" data-hours-closed <?php echo $h['is_closed']?'checked':'';?>>Closed</label><label>Opens<input type="time" name="hours_open[<?php echo craftcrawl_admin_escape($day);?>]" value="<?php echo craftcrawl_admin_escape($h['opens_at']);?>" data-hours-open></label><label>Closes<input type="time" name="hours_close[<?php echo craftcrawl_admin_escape($day);?>]" value="<?php echo craftcrawl_admin_escape($h['closes_at']);?>" data-hours-close></label></div><?php endforeach;?></fieldset><button>Save verified hours</button></form></main></div>
<?php include __DIR__ . '/mobile_nav.php'; ?>
<script src="../js/mobile_actions_menu.js?v=<?php echo filemtime(__DIR__ . '/../js/mobile_actions_menu.js'); ?>"></script>
<script src="../js/depth_animations.js?v=<?php echo filemtime(__DIR__ . '/../js/depth_animations.js'); ?>"></script>
<script src="../js/business_hours_editor.js?v=<?php echo filemtime(__DIR__ . '/../js/business_hours_editor.js'); ?>"></script>
<script>window.CraftCrawlAreaShellConfig = { area: 'admin', home: 'dashboard.php', routes: ['dashboard.php','accounts.php','reviews.php','content.php','account_details.php','review_center.php','location_hours.php','import_locations.php'], active: { 'dashboard.php':'dashboard', 'accounts.php':'accounts', 'account_details.php':'accounts', 'reviews.php':'reviews', 'content.php':'content', 'review_center.php':'dashboard', 'location_hours.php':'dashboard', 'import_locations.php':'dashboard' } };</script>
<script src="../js/area_shell_navigation.js?v=<?php echo filemtime(__DIR__ . '/../js/area_shell_navigation.js'); ?>"></script>
</body></html>
