<?php
require_once __DIR__.'/../lib/admin_auth.php'; require_once __DIR__.'/../lib/admin_review.php'; require_once __DIR__.'/../lib/location_duplicates.php'; require_once __DIR__.'/../lib/location_hours.php'; craftcrawl_require_admin(); include '../db.php';
$admin_id=(int)$_SESSION['admin_id']; $message=$_GET['message']??null;
function admin_redirect($m){header('Location: review_center.php?message='.$m);exit;}
if($_SERVER['REQUEST_METHOD']==='POST'){
 craftcrawl_verify_csrf(); $a=$_POST['form_action']??''; $notes=craftcrawl_admin_clean_text($_POST['admin_notes']??'');

 if(in_array($a,['approve_new_location','reject_new_location'],true)){
  $id=(int)($_POST['location_id']??0); $st=$a==='approve_new_location'?'public_claimed':'rejected';
  $conn->begin_transaction(); $u=$conn->prepare("UPDATE locations SET visibility_status=?,approvedAt=CASE WHEN ?='public_claimed' THEN NOW() ELSE approvedAt END,approvedByAdminId=CASE WHEN ?='public_claimed' THEN ? ELSE approvedByAdminId END WHERE id=?");$u->bind_param('sssii',$st,$st,$st,$admin_id,$id);$u->execute();
  if($st==='public_claimed'){$m=$conn->prepare("UPDATE business_location_managers SET relationship_status='approved',approvedAt=NOW(),approvedByAdminId=? WHERE location_id=? AND relationship_status='pending'");$m->bind_param('ii',$admin_id,$id);$m->execute();$ba=$conn->prepare("UPDATE business_accounts ba INNER JOIN business_location_managers blm ON blm.business_account_id=ba.id SET ba.account_status='approved',ba.approvedAt=NOW(),ba.approvedByAdminId=? WHERE blm.location_id=?");$ba->bind_param('ii',$admin_id,$id);$ba->execute();}
  craftcrawl_log_admin_review_action($conn,$admin_id,'location',$id,$st==='rejected'?'rejected':'approved',$notes);$conn->commit();admin_redirect('new_'.$st);
 }
 if(in_array($a,['approve_claim','reject_claim','more_info_claim'],true)){
  $id=(int)($_POST['claim_id']??0); $claim=$conn->prepare("SELECT * FROM business_claims WHERE id=?");$claim->bind_param('i',$id);$claim->execute();$c=$claim->get_result()->fetch_assoc(); if(!$c) admin_redirect('not_found');
  if($a==='approve_claim'){$conn->begin_transaction();$u=$conn->prepare("UPDATE business_claims SET status='approved',adminNotes=?,reviewedByAdminId=?,reviewedAt=NOW(),updatedAt=NOW() WHERE id=?");$u->bind_param('sii',$notes,$admin_id,$id);$u->execute();$m=$conn->prepare("INSERT INTO business_location_managers (business_account_id,location_id,role_at_location,relationship_status,approvedAt,approvedByAdminId,createdAt) VALUES (?,?,?,'approved',NOW(),?,NOW()) ON DUPLICATE KEY UPDATE relationship_status='approved',role_at_location=VALUES(role_at_location),approvedAt=NOW(),approvedByAdminId=VALUES(approvedByAdminId)");$m->bind_param('iisi',$c['requester_account_id'],$c['location_id'],$c['role_at_location'],$admin_id);$m->execute();$l=$conn->prepare("UPDATE locations SET visibility_status='public_claimed' WHERE id=?");$l->bind_param('i',$c['location_id']);$l->execute();$ba=$conn->prepare("UPDATE business_accounts SET account_status='approved',approvedAt=NOW(),approvedByAdminId=? WHERE id=?");$ba->bind_param('ii',$admin_id,$c['requester_account_id']);$ba->execute();craftcrawl_log_admin_review_action($conn,$admin_id,'business_claim',$id,'approved',$notes);$conn->commit();admin_redirect('claim_approved');}
  $status=$a==='reject_claim'?'rejected':'needs_more_info';$u=$conn->prepare("UPDATE business_claims SET status=?,adminNotes=?,reviewedByAdminId=?,reviewedAt=NOW(),updatedAt=NOW() WHERE id=?");$u->bind_param('ssii',$status,$notes,$admin_id,$id);$u->execute();craftcrawl_log_admin_review_action($conn,$admin_id,'business_claim',$id,$status==='rejected'?'rejected':'needs_more_info',$notes);admin_redirect($status);
 }
 if(in_array($a,['approve_suggestion','reject_suggestion','duplicate_suggestion'],true)){
  $id=(int)($_POST['suggestion_id']??0);$q=$conn->prepare("SELECT * FROM location_suggestions WHERE id=?");$q->bind_param('i',$id);$q->execute();$s=$q->get_result()->fetch_assoc();if(!$s)admin_redirect('not_found');
  if($a==='approve_suggestion'){$nn=craftcrawl_normalize_location_text($s['suggested_name']);$na=craftcrawl_normalize_location_text($s['street_address']);$wd=craftcrawl_location_website_domain($s['website']);$ins=$conn->prepare("INSERT INTO locations (name,phone,street_address,apt_suite,city,state,zip,latitude,longitude,website,location_type,visibility_status,source_provider,source_place_id,normalized_name,normalized_address,website_domain,approvedAt,approvedByAdminId,createdAt) VALUES (?,?,?,?,?,?,?,?,?,?,?,'public_unclaimed','user_suggested',?,?,?,?,NOW(),?,NOW())");$ins->bind_param('sssssssddssssssi',$s['suggested_name'],$s['phone'],$s['street_address'],$s['apt_suite'],$s['city'],$s['state'],$s['zip'],$s['latitude'],$s['longitude'],$s['website'],$s['suggested_type'],$s['mapbox_place_id'],$nn,$na,$wd,$admin_id);$ins->execute();$lid=$ins->insert_id;$u=$conn->prepare("UPDATE location_suggestions SET status='approved',created_location_id=?,adminNotes=?,reviewedByAdminId=?,reviewedAt=NOW(),updatedAt=NOW() WHERE id=?");$u->bind_param('isii',$lid,$notes,$admin_id,$id);$u->execute();craftcrawl_log_admin_review_action($conn,$admin_id,'location_suggestion',$id,'approved',$notes);admin_redirect('suggestion_approved');}
  $st=$a==='reject_suggestion'?'rejected':'duplicate';$matched=(int)($_POST['matched_location_id']??0)?:null;$u=$conn->prepare("UPDATE location_suggestions SET status=?,matched_location_id=?,adminNotes=?,reviewedByAdminId=?,reviewedAt=NOW(),updatedAt=NOW() WHERE id=?");$u->bind_param('sisii',$st,$matched,$notes,$admin_id,$id);$u->execute();craftcrawl_log_admin_review_action($conn,$admin_id,'location_suggestion',$id,$st==='duplicate'?'marked_duplicate':'rejected',$notes);admin_redirect('suggestion_'.$st);
 }
 if($a==='import_location'){
  $name=craftcrawl_admin_clean_text($_POST['name']??'');$place=craftcrawl_admin_clean_text($_POST['source_place_id']??'');$addr=craftcrawl_admin_clean_text($_POST['street_address']??'');$city=craftcrawl_admin_clean_text($_POST['city']??'');$state=craftcrawl_admin_clean_text($_POST['state']??'');$type=craftcrawl_admin_clean_text($_POST['location_type']??'');$lat=(float)($_POST['latitude']??0);$lng=(float)($_POST['longitude']??0); if(!$name||!$place||!$addr||!$city||!$state||!$type||!$lat||!$lng)admin_redirect('import_invalid');
  $nn=craftcrawl_normalize_location_text($name);$na=craftcrawl_normalize_location_text($addr);$i=$conn->prepare("INSERT INTO locations (name,street_address,city,state,zip,latitude,longitude,location_type,visibility_status,source_provider,source_place_id,normalized_name,normalized_address,importedAt,createdAt) VALUES (?,?,?,?,?,?,?,?,'pending_import_review','mapbox',?,?,?,NOW(),NOW())");$zip=$_POST['zip']??'';$i->bind_param('sssssddssss',$name,$addr,$city,$state,$zip,$lat,$lng,$type,$place,$nn,$na);$i->execute();admin_redirect('import_added');
 }
 if(in_array($a,['approve_import','reject_import'],true)){$id=(int)$_POST['location_id'];$st=$a==='approve_import'?'public_unclaimed':'rejected';$u=$conn->prepare("UPDATE locations SET visibility_status=?,approvedAt=CASE WHEN ?='public_unclaimed' THEN NOW() ELSE approvedAt END,approvedByAdminId=CASE WHEN ?='public_unclaimed' THEN ? ELSE approvedByAdminId END WHERE id=?");$u->bind_param('sssii',$st,$st,$st,$admin_id,$id);$u->execute();craftcrawl_log_admin_review_action($conn,$admin_id,'location',$id,$st==='rejected'?'rejected':'approved',$notes);admin_redirect('import_'.$st);}
 if($a==='enable_checkins'){$id=(int)$_POST['location_id']; if(!craftcrawl_location_has_verified_hours($conn,$id)) admin_redirect('hours_required');$u=$conn->prepare("UPDATE locations SET checkin_verification_enabled=TRUE,checkin_enabled_at=NOW(),checkin_enabled_by_admin_id=? WHERE id=?");$u->bind_param('ii',$admin_id,$id);$u->execute();craftcrawl_log_admin_review_action($conn,$admin_id,'location',$id,'checkins_enabled',$notes);admin_redirect('checkins_enabled');}
}
$new_locations=$conn->query("SELECT l.*, ba.account_email FROM locations l LEFT JOIN business_location_managers blm ON blm.location_id=l.id LEFT JOIN business_accounts ba ON ba.id=blm.business_account_id WHERE l.visibility_status='pending_new_business' ORDER BY l.createdAt");
$claims=$conn->query("SELECT bc.*,l.name,ba.account_email FROM business_claims bc INNER JOIN locations l ON l.id=bc.location_id INNER JOIN business_accounts ba ON ba.id=bc.requester_account_id WHERE bc.status IN ('pending','needs_more_info') ORDER BY bc.createdAt");
$suggestions=$conn->query("SELECT ls.*,u.fName,u.lName FROM location_suggestions ls INNER JOIN users u ON u.id=ls.suggested_by_user_id WHERE ls.status='pending' ORDER BY ls.createdAt");
$imports=$conn->query("SELECT * FROM locations WHERE visibility_status='pending_import_review' ORDER BY createdAt");
$readiness=$conn->query("SELECT l.* FROM locations l WHERE l.visibility_status IN ('public_unclaimed','public_claimed') AND l.checkin_verification_enabled=FALSE ORDER BY l.name");
?>
<!doctype html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Admin Review Center</title><link rel="stylesheet" href="../css/style.css?v=<?php echo filemtime(__DIR__.'/../css/style.css');?>"></head><body><main class="business-portal admin-page"><header class="business-portal-header"><h1>Review Center</h1><a href="dashboard.php">Dashboard</a></header>
<section class="admin-panel"><h2>New Business Submissions</h2><?php while($l=$new_locations->fetch_assoc()):?><article class="admin-list-item"><div><h3><?php echo craftcrawl_admin_escape($l['name']);?></h3><p><?php echo craftcrawl_admin_escape($l['account_email'] . ' · ' . $l['city'] . ', ' . $l['state']);?></p></div><form method="POST"><?php echo craftcrawl_csrf_input();?><input type="hidden" name="location_id" value="<?php echo $l['id'];?>"><textarea name="admin_notes"></textarea><button name="form_action" value="approve_new_location">Approve</button><button name="form_action" value="reject_new_location">Reject</button></form></article><?php endwhile;?></section>
<section class="admin-panel"><h2>Pending Claims</h2><?php while($c=$claims->fetch_assoc()):?><article class="admin-list-item"><div><h3><?php echo craftcrawl_admin_escape($c['name']);?></h3><p><?php echo craftcrawl_admin_escape($c['account_email'].' · '.$c['contact_name'].' · '.$c['verification_method']);?></p><p><?php echo nl2br(craftcrawl_admin_escape($c['verification_notes']));?></p></div><form method="POST"><?php echo craftcrawl_csrf_input();?><input type="hidden" name="claim_id" value="<?php echo $c['id'];?>"><textarea name="admin_notes" placeholder="Notes / request"></textarea><button name="form_action" value="approve_claim">Approve</button><button name="form_action" value="more_info_claim">Request more info</button><button name="form_action" value="reject_claim">Reject</button></form></article><?php endwhile;?></section>
<section class="admin-panel"><h2>Pending Suggestions</h2><?php while($s=$suggestions->fetch_assoc()):?><article class="admin-list-item"><div><h3><?php echo craftcrawl_admin_escape($s['suggested_name']);?></h3><p><?php echo craftcrawl_admin_escape($s['street_address'].', '.$s['city'].', '.$s['state']);?> · by <?php echo craftcrawl_admin_escape($s['fName'].' '.$s['lName']);?></p></div><form method="POST"><?php echo craftcrawl_csrf_input();?><input type="hidden" name="suggestion_id" value="<?php echo $s['id'];?>"><input name="matched_location_id" placeholder="Existing location ID if duplicate"><textarea name="admin_notes"></textarea><button name="form_action" value="approve_suggestion">Approve</button><button name="form_action" value="duplicate_suggestion">Mark duplicate</button><button name="form_action" value="reject_suggestion">Reject</button></form></article><?php endwhile;?></section>
<section class="admin-panel"><h2>Import Location</h2><form method="POST"><?php echo craftcrawl_csrf_input();?><input type="hidden" name="form_action" value="import_location"><input name="name" placeholder="Name" required><input name="source_place_id" placeholder="Mapbox place id" required><input name="location_type" placeholder="Type" required><input name="street_address" placeholder="Address" required><input name="city" placeholder="City" required><input name="state" placeholder="State" required><input name="zip" placeholder="ZIP"><input name="latitude" placeholder="Latitude" required><input name="longitude" placeholder="Longitude" required><button>Import for review</button></form></section>
<section class="admin-panel"><h2>Pending Imported Locations</h2><?php while($l=$imports->fetch_assoc()):?><article class="admin-list-item"><div><h3><?php echo craftcrawl_admin_escape($l['name']);?></h3><p><?php echo craftcrawl_admin_escape($l['street_address'].', '.$l['city']);?></p></div><form method="POST"><?php echo craftcrawl_csrf_input();?><input type="hidden" name="location_id" value="<?php echo $l['id'];?>"><textarea name="admin_notes"></textarea><button name="form_action" value="approve_import">Approve public listing</button><button name="form_action" value="reject_import">Reject</button></form></article><?php endwhile;?></section>
<section class="admin-panel"><h2>Check-in Readiness</h2><?php while($l=$readiness->fetch_assoc()):?><article class="admin-list-item"><div><h3><?php echo craftcrawl_admin_escape($l['name']);?></h3><p><?php echo craftcrawl_admin_escape($l['city'].', '.$l['state']);?></p></div><div><a href="location_hours.php?id=<?php echo $l['id'];?>">Edit hours</a><form method="POST"><?php echo craftcrawl_csrf_input();?><input type="hidden" name="location_id" value="<?php echo $l['id'];?>"><button name="form_action" value="enable_checkins">Enable check-ins</button></form></div></article><?php endwhile;?></section></main></body></html>
