<?php
require_once __DIR__.'/../lib/admin_auth.php'; require_once __DIR__.'/../lib/admin_review.php'; require_once __DIR__.'/../lib/location_duplicates.php'; require_once __DIR__.'/../lib/location_hours.php'; craftcrawl_require_admin(); include '../db.php';
$admin_id=(int)$_SESSION['admin_id']; $message=$_GET['message']??null;
function admin_redirect($m){header('Location: review_center.php?message='.$m);exit;}
function admin_location_candidate(array $row, $source_provider = null, $source_place_id = null) {
 return [
  'name'=>$row['name']??$row['suggested_name']??'',
  'address'=>$row['street_address']??'',
  'phone'=>$row['phone']??'',
  'website'=>$row['website']??'',
  'latitude'=>$row['latitude']??null,
  'longitude'=>$row['longitude']??null,
  'source_provider'=>$source_provider??($row['source_provider']??null),
  'source_place_id'=>$source_place_id??($row['source_place_id']??null),
  'exclude_location_id'=>$row['id']??0,
 ];
}
function admin_duplicate_summary_for_candidate($conn, array $candidate){return craftcrawl_location_duplicate_summary(craftcrawl_location_duplicate_candidates($conn,$candidate));}
function admin_has_soft_duplicate(array $summary){return !empty($summary['soft_block']);}
function admin_has_hard_duplicate(array $summary){return !empty($summary['hard_block']);}
function admin_render_duplicate_summary(array $summary){
 if(empty($summary['hard_block'])&&empty($summary['soft_block'])&&empty($summary['warning']))return;
 echo '<div class="admin-duplicate-summary">';
 foreach(['hard_block'=>'Hard block','soft_block'=>'Needs confirmation','warning'=>'Warning'] as $confidence=>$label){
  if(empty($summary[$confidence]))continue;
  echo '<p class="admin-duplicate-'.$confidence.'"><strong>'.craftcrawl_admin_escape($label).':</strong> ';
  $bits=[]; foreach($summary[$confidence] as $m){$bits[]='#'.$m['id'].' '.$m['name'].' ('.str_replace('_',' ',$m['match_type']).')';}
  echo craftcrawl_admin_escape(implode('; ',$bits)).'</p>';
 }
 echo '</div>';
}
if($_SERVER['REQUEST_METHOD']==='POST'){
 craftcrawl_verify_csrf(); $a=$_POST['form_action']??''; $notes=craftcrawl_admin_clean_text($_POST['admin_notes']??'');
 if($a==='save_location_notes'){$id=(int)($_POST['location_id']??0);$u=$conn->prepare("UPDATE locations SET adminNotes=? WHERE id=?");$u->bind_param('si',$notes,$id);$u->execute();admin_redirect('location_notes_saved');}
 if($a==='save_claim_notes'){$id=(int)($_POST['claim_id']??0);$u=$conn->prepare("UPDATE business_claims SET adminNotes=?,updatedAt=NOW() WHERE id=?");$u->bind_param('si',$notes,$id);$u->execute();admin_redirect('claim_notes_saved');}
 if($a==='save_suggestion_notes'){$id=(int)($_POST['suggestion_id']??0);$u=$conn->prepare("UPDATE location_suggestions SET adminNotes=?,updatedAt=NOW() WHERE id=?");$u->bind_param('si',$notes,$id);$u->execute();admin_redirect('suggestion_notes_saved');}

 if(in_array($a,['approve_new_location','reject_new_location','more_info_new_location'],true)){
  $id=(int)($_POST['location_id']??0);
  if($a==='more_info_new_location'){$u=$conn->prepare("UPDATE locations SET submission_review_status='needs_more_info',adminNotes=? WHERE id=?");$u->bind_param('si',$notes,$id);$u->execute();craftcrawl_log_admin_review_action($conn,$admin_id,'location',$id,'needs_more_info',$notes);admin_redirect('new_needs_more_info');}
  $st=$a==='approve_new_location'?'public_claimed':'rejected';
  if($a==='approve_new_location'){$q=$conn->prepare("SELECT * FROM locations WHERE id=?");$q->bind_param('i',$id);$q->execute();$location=$q->get_result()->fetch_assoc();$dupes=$location?admin_duplicate_summary_for_candidate($conn,admin_location_candidate($location)):[];if(admin_has_hard_duplicate($dupes))admin_redirect('duplicate_hard_block');if(admin_has_soft_duplicate($dupes)&&empty($_POST['confirm_soft_duplicate']))admin_redirect('duplicate_confirmation_required');}
  $review_status=$st==='public_claimed'?'approved':'rejected';
  $conn->begin_transaction(); $u=$conn->prepare("UPDATE locations SET visibility_status=?,submission_review_status=?,adminNotes=?,approvedAt=CASE WHEN ?='public_claimed' THEN NOW() ELSE approvedAt END,approvedByAdminId=CASE WHEN ?='public_claimed' THEN ? ELSE approvedByAdminId END WHERE id=?");$u->bind_param('sssssii',$st,$review_status,$notes,$st,$st,$admin_id,$id);$u->execute();
  if($st==='public_claimed'){$m=$conn->prepare("UPDATE business_location_managers SET relationship_status='approved',approvedAt=NOW(),approvedByAdminId=? WHERE location_id=? AND relationship_status='pending'");$m->bind_param('ii',$admin_id,$id);$m->execute();$ba=$conn->prepare("UPDATE business_accounts ba INNER JOIN business_location_managers blm ON blm.business_account_id=ba.id SET ba.account_status='approved',ba.approvedAt=NOW(),ba.approvedByAdminId=? WHERE blm.location_id=?");$ba->bind_param('ii',$admin_id,$id);$ba->execute();}
  craftcrawl_log_admin_review_action($conn,$admin_id,'location',$id,$st==='rejected'?'rejected':'approved',$notes);$conn->commit();admin_redirect('new_'.$st);
 }
 if(in_array($a,['approve_claim','reject_claim','more_info_claim','cancel_claim'],true)){
  $id=(int)($_POST['claim_id']??0); $claim=$conn->prepare("SELECT * FROM business_claims WHERE id=?");$claim->bind_param('i',$id);$claim->execute();$c=$claim->get_result()->fetch_assoc(); if(!$c) admin_redirect('not_found');
  if($a==='approve_claim'){$conn->begin_transaction();$u=$conn->prepare("UPDATE business_claims SET status='approved',adminNotes=?,reviewedByAdminId=?,reviewedAt=NOW(),updatedAt=NOW() WHERE id=?");$u->bind_param('sii',$notes,$admin_id,$id);$u->execute();$m=$conn->prepare("INSERT INTO business_location_managers (business_account_id,location_id,role_at_location,relationship_status,approvedAt,approvedByAdminId,createdAt) VALUES (?,?,?,'approved',NOW(),?,NOW()) ON DUPLICATE KEY UPDATE relationship_status='approved',role_at_location=VALUES(role_at_location),approvedAt=NOW(),approvedByAdminId=VALUES(approvedByAdminId)");$m->bind_param('iisi',$c['requester_account_id'],$c['location_id'],$c['role_at_location'],$admin_id);$m->execute();$l=$conn->prepare("UPDATE locations SET visibility_status='public_claimed' WHERE id=?");$l->bind_param('i',$c['location_id']);$l->execute();$ba=$conn->prepare("UPDATE business_accounts SET account_status='approved',approvedAt=NOW(),approvedByAdminId=? WHERE id=?");$ba->bind_param('ii',$admin_id,$c['requester_account_id']);$ba->execute();craftcrawl_log_admin_review_action($conn,$admin_id,'business_claim',$id,'approved',$notes);$conn->commit();admin_redirect('claim_approved');}
  $status=$a==='reject_claim'?'rejected':($a==='cancel_claim'?'cancelled':'needs_more_info');$u=$conn->prepare("UPDATE business_claims SET status=?,adminNotes=?,reviewedByAdminId=?,reviewedAt=NOW(),updatedAt=NOW() WHERE id=?");$u->bind_param('ssii',$status,$notes,$admin_id,$id);$u->execute();craftcrawl_log_admin_review_action($conn,$admin_id,'business_claim',$id,$status,$notes);admin_redirect($status);
 }
 if(in_array($a,['approve_suggestion','reject_suggestion','duplicate_suggestion'],true)){
  $id=(int)($_POST['suggestion_id']??0);$q=$conn->prepare("SELECT * FROM location_suggestions WHERE id=?");$q->bind_param('i',$id);$q->execute();$s=$q->get_result()->fetch_assoc();if(!$s)admin_redirect('not_found');
  if($a==='approve_suggestion'){$dupes=admin_duplicate_summary_for_candidate($conn,admin_location_candidate($s,'user_suggested',$s['mapbox_place_id']));if(admin_has_hard_duplicate($dupes))admin_redirect('duplicate_hard_block');if(admin_has_soft_duplicate($dupes)&&empty($_POST['confirm_soft_duplicate']))admin_redirect('duplicate_confirmation_required');$nn=craftcrawl_normalize_location_text($s['suggested_name']);$na=craftcrawl_normalize_location_text($s['street_address']);$wd=craftcrawl_location_website_domain($s['website']);$location_admin_notes=trim((string)($s['user_notes']??''));$ins=$conn->prepare("INSERT INTO locations (name,phone,street_address,apt_suite,city,state,zip,latitude,longitude,website,location_type,visibility_status,source_provider,source_place_id,normalized_name,normalized_address,website_domain,adminNotes,approvedAt,approvedByAdminId,createdAt) VALUES (?,?,?,?,?,?,?,?,?,?,?,'public_unclaimed','user_suggested',?,?,?,?,?,NOW(),?,NOW())");$ins->bind_param('sssssssddsssssssi',$s['suggested_name'],$s['phone'],$s['street_address'],$s['apt_suite'],$s['city'],$s['state'],$s['zip'],$s['latitude'],$s['longitude'],$s['website'],$s['suggested_type'],$s['mapbox_place_id'],$nn,$na,$wd,$location_admin_notes,$admin_id);$ins->execute();$lid=$ins->insert_id;$u=$conn->prepare("UPDATE location_suggestions SET status='approved',created_location_id=?,adminNotes=?,reviewedByAdminId=?,reviewedAt=NOW(),updatedAt=NOW() WHERE id=?");$u->bind_param('isii',$lid,$notes,$admin_id,$id);$u->execute();craftcrawl_log_admin_review_action($conn,$admin_id,'location_suggestion',$id,'approved',$notes);admin_redirect('suggestion_approved');}
  $st=$a==='reject_suggestion'?'rejected':'duplicate';$matched=(int)($_POST['matched_location_id']??0)?:null;$u=$conn->prepare("UPDATE location_suggestions SET status=?,matched_location_id=?,adminNotes=?,reviewedByAdminId=?,reviewedAt=NOW(),updatedAt=NOW() WHERE id=?");$u->bind_param('sisii',$st,$matched,$notes,$admin_id,$id);$u->execute();craftcrawl_log_admin_review_action($conn,$admin_id,'location_suggestion',$id,$st==='duplicate'?'marked_duplicate':'rejected',$notes);admin_redirect('suggestion_'.$st);
 }
 if($a==='import_location'){
  $name=craftcrawl_admin_clean_text($_POST['name']??'');$place=craftcrawl_admin_clean_text($_POST['source_place_id']??'');$addr=craftcrawl_admin_clean_text($_POST['street_address']??'');$city=craftcrawl_admin_clean_text($_POST['city']??'');$state=craftcrawl_admin_clean_text($_POST['state']??'');$type=craftcrawl_admin_clean_text($_POST['location_type']??'');$lat=(float)($_POST['latitude']??0);$lng=(float)($_POST['longitude']??0); if(!$name||!$place||!$addr||!$city||!$state||!$type||!$lat||!$lng)admin_redirect('import_invalid');
  $candidate=['name'=>$name,'address'=>$addr,'latitude'=>$lat,'longitude'=>$lng,'source_provider'=>'mapbox','source_place_id'=>$place];$dupes=admin_duplicate_summary_for_candidate($conn,$candidate);if(admin_has_hard_duplicate($dupes))admin_redirect('duplicate_hard_block');if(admin_has_soft_duplicate($dupes)&&empty($_POST['confirm_soft_duplicate']))admin_redirect('duplicate_confirmation_required');
  $nn=craftcrawl_normalize_location_text($name);$na=craftcrawl_normalize_location_text($addr);$i=$conn->prepare("INSERT INTO locations (name,street_address,city,state,zip,latitude,longitude,location_type,visibility_status,source_provider,source_place_id,normalized_name,normalized_address,importedAt,createdAt) VALUES (?,?,?,?,?,?,?,?,'pending_import_review','mapbox',?,?,?,NOW(),NOW())");$zip=$_POST['zip']??'';$i->bind_param('sssssddssss',$name,$addr,$city,$state,$zip,$lat,$lng,$type,$place,$nn,$na);$i->execute();admin_redirect('import_added');
 }
 if(in_array($a,['approve_import','reject_import'],true)){$id=(int)$_POST['location_id'];if($a==='approve_import'){$q=$conn->prepare("SELECT * FROM locations WHERE id=?");$q->bind_param('i',$id);$q->execute();$location=$q->get_result()->fetch_assoc();$dupes=$location?admin_duplicate_summary_for_candidate($conn,admin_location_candidate($location)):[];if(admin_has_hard_duplicate($dupes))admin_redirect('duplicate_hard_block');if(admin_has_soft_duplicate($dupes)&&empty($_POST['confirm_soft_duplicate']))admin_redirect('duplicate_confirmation_required');}$st=$a==='approve_import'?'public_unclaimed':'rejected';$u=$conn->prepare("UPDATE locations SET visibility_status=?,adminNotes=?,approvedAt=CASE WHEN ?='public_unclaimed' THEN NOW() ELSE approvedAt END,approvedByAdminId=CASE WHEN ?='public_unclaimed' THEN ? ELSE approvedByAdminId END WHERE id=?");$u->bind_param('ssssii',$st,$notes,$st,$st,$admin_id,$id);$u->execute();craftcrawl_log_admin_review_action($conn,$admin_id,'location',$id,$st==='rejected'?'rejected':'approved',$notes);admin_redirect('import_'.$st);}
 if($a==='enable_checkins'){$id=(int)$_POST['location_id']; if(!craftcrawl_location_has_verified_hours($conn,$id)) admin_redirect('hours_required');$u=$conn->prepare("UPDATE locations SET adminNotes=?,checkin_verification_enabled=TRUE,checkin_enabled_at=NOW(),checkin_enabled_by_admin_id=? WHERE id=?");$u->bind_param('sii',$notes,$admin_id,$id);$u->execute();craftcrawl_log_admin_review_action($conn,$admin_id,'location',$id,'checkins_enabled',$notes);admin_redirect('checkins_enabled');}
 if($a==='restore_suggestion'){$id=(int)($_POST['suggestion_id']??0);$u=$conn->prepare("UPDATE location_suggestions SET status='pending',matched_location_id=NULL,adminNotes=?,reviewedByAdminId=NULL,reviewedAt=NULL,updatedAt=NOW() WHERE id=? AND status IN ('rejected','duplicate')");$u->bind_param('si',$notes,$id);$u->execute();craftcrawl_log_admin_review_action($conn,$admin_id,'location_suggestion',$id,'unhidden',$notes);admin_redirect('suggestion_restored');}
 if(in_array($a,['hide_location','unhide_location'],true)){$id=(int)($_POST['location_id']??0);$st=$a==='hide_location'?'hidden':'public_unclaimed';$u=$conn->prepare("UPDATE locations SET visibility_status=?,adminNotes=? WHERE id=?");$u->bind_param('ssi',$st,$notes,$id);$u->execute();craftcrawl_log_admin_review_action($conn,$admin_id,'location',$id,$a==='hide_location'?'hidden':'unhidden',$notes);admin_redirect($st);}
}
$new_locations=$conn->query("SELECT l.*, ba.account_email FROM locations l LEFT JOIN business_location_managers blm ON blm.location_id=l.id LEFT JOIN business_accounts ba ON ba.id=blm.business_account_id WHERE l.visibility_status='pending_new_business' ORDER BY l.createdAt");
$claims=$conn->query("SELECT bc.*,l.name,ba.account_email,(SELECT COUNT(*) FROM business_claims bc2 WHERE bc2.location_id=bc.location_id AND bc2.status IN ('pending','needs_more_info')) AS active_claim_count,(SELECT COUNT(*) FROM business_location_managers blm WHERE blm.location_id=bc.location_id AND blm.relationship_status='approved' AND blm.disabledAt IS NULL) AS approved_manager_count FROM business_claims bc INNER JOIN locations l ON l.id=bc.location_id INNER JOIN business_accounts ba ON ba.id=bc.requester_account_id WHERE bc.status IN ('pending','needs_more_info') ORDER BY bc.location_id, bc.createdAt");
$suggestions=$conn->query("SELECT ls.*,u.fName,u.lName FROM location_suggestions ls INNER JOIN users u ON u.id=ls.suggested_by_user_id WHERE ls.status='pending' ORDER BY ls.createdAt");
$imports=$conn->query("SELECT * FROM locations WHERE visibility_status='pending_import_review' ORDER BY createdAt");
$readiness=$conn->query("SELECT l.*, ls.user_notes AS suggestion_user_notes FROM locations l LEFT JOIN location_suggestions ls ON ls.created_location_id=l.id WHERE l.visibility_status IN ('public_unclaimed','public_claimed') AND l.checkin_verification_enabled=FALSE AND NOT EXISTS (SELECT 1 FROM location_hours lh WHERE lh.location_id=l.id AND (lh.verifiedAt IS NOT NULL OR lh.source='business_owner')) ORDER BY l.name");
$rejected_hidden=$conn->query("SELECT 'location' AS recovery_type,l.id AS location_id,NULL AS suggestion_id,l.name,l.location_type,l.visibility_status AS review_status,l.street_address,l.apt_suite,l.city,l.state,l.zip,l.adminNotes,l.createdAt,NULL AS user_notes,NULL AS mapbox_place_id,NULL AS suggested_by,NULL AS matched_location_id FROM locations l WHERE l.visibility_status IN ('rejected','hidden') UNION ALL SELECT 'suggestion' AS recovery_type,NULL AS location_id,ls.id AS suggestion_id,ls.suggested_name AS name,ls.suggested_type AS location_type,ls.status AS review_status,ls.street_address,ls.apt_suite,ls.city,ls.state,ls.zip,ls.adminNotes,COALESCE(ls.reviewedAt,ls.createdAt) AS createdAt,ls.user_notes,ls.mapbox_place_id,CONCAT(u.fName,' ',u.lName) AS suggested_by,ls.matched_location_id FROM location_suggestions ls INNER JOIN users u ON u.id=ls.suggested_by_user_id WHERE ls.status IN ('rejected','duplicate') ORDER BY createdAt DESC");
?>
<!doctype html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Admin Approval Center</title><link rel="stylesheet" href="../css/style.css?v=<?php echo filemtime(__DIR__.'/../css/style.css');?>"><?php require_once dirname(__DIR__) . '/lib/google_analytics.php'; echo craftcrawl_google_analytics_tag(); ?></head><body><div data-area-page-content><main class="business-portal admin-page"><header class="business-portal-header"><h1>Approval Center</h1><a href="dashboard.php">Dashboard</a></header>
<section class="admin-panel"><h2>New Business Submissions</h2><?php while($l=$new_locations->fetch_assoc()):$dupes=admin_duplicate_summary_for_candidate($conn,admin_location_candidate($l));?><article class="admin-list-item"><div><h3><?php echo craftcrawl_admin_escape($l['name']);?></h3><p><?php echo craftcrawl_admin_escape($l['account_email'] . ' · ' . $l['city'] . ', ' . $l['state']);?></p><p>Status: <?php echo craftcrawl_admin_escape(ucwords(str_replace('_',' ',$l['submission_review_status'])));?></p><?php if(!empty($l['submission_response_notes'])):?><p>Business response: <?php echo nl2br(craftcrawl_admin_escape($l['submission_response_notes']));?></p><?php endif;?><?php admin_render_duplicate_summary($dupes);?></div><form method="POST"><?php echo craftcrawl_csrf_input();?><input type="hidden" name="location_id" value="<?php echo $l['id'];?>"><?php if(admin_has_soft_duplicate($dupes)):?><label><input type="checkbox" name="confirm_soft_duplicate" value="1"> Create anyway after duplicate review</label><?php endif;?><textarea name="admin_notes" placeholder="Notes / request"><?php echo craftcrawl_admin_escape($l['adminNotes']??'');?></textarea><button name="form_action" value="save_location_notes">Save notes</button><button name="form_action" value="approve_new_location">Approve</button><button name="form_action" value="more_info_new_location">Request more info</button><button name="form_action" value="reject_new_location">Reject</button></form></article><?php endwhile;?></section>
<section class="admin-panel"><h2>Pending Claims</h2><?php while($c=$claims->fetch_assoc()):?><article class="admin-list-item"><div><h3><?php echo craftcrawl_admin_escape($c['name']);?></h3><p><?php echo craftcrawl_admin_escape($c['account_email'].' · '.$c['contact_name'].' · '.$c['role_at_location'].' · '.$c['verification_method']);?></p><p><?php echo craftcrawl_admin_escape($c['active_claim_count'].' active claim'.((int)$c['active_claim_count']===1?'':'s').' · '.$c['approved_manager_count'].' approved manager'.((int)$c['approved_manager_count']===1?'':'s'));?></p><?php if(!empty($c['official_social_url'])):?><p><?php echo craftcrawl_admin_escape($c['official_social_url']);?></p><?php endif;?><p><?php echo nl2br(craftcrawl_admin_escape($c['verification_notes']));?></p></div><form method="POST"><?php echo craftcrawl_csrf_input();?><input type="hidden" name="claim_id" value="<?php echo $c['id'];?>"><textarea name="admin_notes" placeholder="Notes / request"><?php echo craftcrawl_admin_escape($c['adminNotes']??'');?></textarea><button name="form_action" value="save_claim_notes">Save notes</button><button name="form_action" value="approve_claim">Approve</button><button name="form_action" value="more_info_claim">Request more info</button><button name="form_action" value="reject_claim">Reject</button><button name="form_action" value="cancel_claim">Cancel</button></form></article><?php endwhile;?></section>
<section class="admin-panel"><h2>Pending Suggestions</h2><?php while($s=$suggestions->fetch_assoc()):$dupes=admin_duplicate_summary_for_candidate($conn,admin_location_candidate($s,'user_suggested',$s['mapbox_place_id']));$full_address=trim(implode(', ',array_filter([$s['street_address'], $s['apt_suite'], $s['city'], $s['state'], $s['zip']])));?><article class="admin-list-item admin-suggestion-review-item"><div class="admin-suggestion-details"><h3><?php echo craftcrawl_admin_escape($s['suggested_name']);?></h3><p><?php echo craftcrawl_admin_escape(craftcrawl_admin_business_type_label($s['suggested_type']));?> · suggested by <?php echo craftcrawl_admin_escape($s['fName'].' '.$s['lName']);?></p><p><strong>Address:</strong> <?php echo craftcrawl_admin_escape($full_address);?></p><?php if(!empty($s['phone'])):?><p><strong>Phone:</strong> <?php echo craftcrawl_admin_escape($s['phone']);?></p><?php endif;?><?php if(!empty($s['website'])):?><p><strong>Website:</strong> <?php echo craftcrawl_admin_escape($s['website']);?></p><?php endif;?><?php if(!empty($s['user_notes'])):?><p><strong>User notes:</strong> <?php echo nl2br(craftcrawl_admin_escape($s['user_notes']));?></p><?php endif;?><p><strong>Mapbox ID:</strong> <?php echo craftcrawl_admin_escape($s['mapbox_place_id']);?></p><?php admin_render_duplicate_summary($dupes);?></div><form class="admin-suggestion-review-form" method="POST"><?php echo craftcrawl_csrf_input();?><input type="hidden" name="suggestion_id" value="<?php echo $s['id'];?>"><input name="matched_location_id" placeholder="Existing location ID if duplicate"><?php if(admin_has_soft_duplicate($dupes)):?><label><input type="checkbox" name="confirm_soft_duplicate" value="1"> Create anyway after duplicate review</label><?php endif;?><textarea name="admin_notes" placeholder="Admin notes"><?php echo craftcrawl_admin_escape($s['adminNotes']??'');?></textarea><div class="admin-suggestion-review-actions"><button name="form_action" value="save_suggestion_notes">Save notes</button><button name="form_action" value="approve_suggestion">Approve</button><button name="form_action" value="duplicate_suggestion">Mark duplicate</button><button name="form_action" value="reject_suggestion">Reject</button></div></form></article><?php endwhile;?></section>
<section class="admin-panel"><h2>Import Location</h2><p><a href="import_locations.php">Search Mapbox for import candidates</a></p></section>
<section class="admin-panel"><h2>Pending Imported Locations</h2><?php while($l=$imports->fetch_assoc()):$dupes=admin_duplicate_summary_for_candidate($conn,admin_location_candidate($l));$full_address=trim(implode(', ',array_filter([$l['street_address'], $l['apt_suite'], $l['city'], $l['state'], $l['zip']])));?><article class="admin-list-item admin-import-review-item"><div class="admin-import-details"><h3><?php echo craftcrawl_admin_escape($l['name']);?></h3><p><?php echo craftcrawl_admin_escape(craftcrawl_admin_business_type_label($l['location_type']));?> · Mapbox import candidate</p><p><strong>Address:</strong> <?php echo craftcrawl_admin_escape($full_address);?></p><?php if(!empty($l['phone'])):?><p><strong>Phone:</strong> <?php echo craftcrawl_admin_escape($l['phone']);?></p><?php endif;?><?php if(!empty($l['website'])):?><p><strong>Website:</strong> <?php echo craftcrawl_admin_escape($l['website']);?></p><?php endif;?><p><strong>Mapbox ID:</strong> <?php echo craftcrawl_admin_escape($l['source_place_id']);?></p><?php admin_render_duplicate_summary($dupes);?></div><form class="admin-import-review-form" method="POST"><?php echo craftcrawl_csrf_input();?><input type="hidden" name="location_id" value="<?php echo $l['id'];?>"><?php if(admin_has_soft_duplicate($dupes)):?><label><input type="checkbox" name="confirm_soft_duplicate" value="1"> Approve anyway after duplicate review</label><?php endif;?><textarea name="admin_notes" placeholder="Admin notes"><?php echo craftcrawl_admin_escape($l['adminNotes']??'');?></textarea><div class="admin-import-review-actions"><button name="form_action" value="save_location_notes">Save notes</button><button name="form_action" value="approve_import">Approve public listing</button><button name="form_action" value="reject_import">Reject</button></div></form></article><?php endwhile;?></section>
<section class="admin-panel"><h2>Check-in Readiness</h2><?php while($l=$readiness->fetch_assoc()):$full_address=trim(implode(', ',array_filter([$l['street_address'], $l['apt_suite'], $l['city'], $l['state'], $l['zip']])));$hours=craftcrawl_location_hours_for_form($conn,(int)$l['id']);$hours_text=craftcrawl_business_hours_have_saved_hours($hours)?craftcrawl_format_business_hours($hours):'';$has_verified_hours=craftcrawl_location_has_verified_hours($conn,(int)$l['id']);?><article class="admin-list-item admin-readiness-review-item"><div class="admin-readiness-details"><h3><?php echo craftcrawl_admin_escape($l['name']);?></h3><p><?php echo craftcrawl_admin_escape(craftcrawl_admin_business_type_label($l['location_type']));?> · <?php echo craftcrawl_admin_escape(ucwords(str_replace('_',' ',$l['visibility_status'])));?></p><p><strong>Address:</strong> <?php echo craftcrawl_admin_escape($full_address);?></p><?php if(!empty($l['phone'])):?><p><strong>Phone:</strong> <?php echo craftcrawl_admin_escape($l['phone']);?></p><?php endif;?><?php if(!empty($l['website'])):?><p><strong>Website:</strong> <?php echo craftcrawl_admin_escape($l['website']);?></p><?php endif;?><?php if(!empty($l['source_place_id'])):?><p><strong>Mapbox ID:</strong> <?php echo craftcrawl_admin_escape($l['source_place_id']);?></p><?php endif;?><p><strong>Hours:</strong> <?php echo $has_verified_hours?'Verified':'Not verified';?></p><?php if($hours_text!==''):?><p class="admin-readiness-hours"><?php echo nl2br(craftcrawl_admin_escape($hours_text));?></p><?php endif;?></div><form class="admin-readiness-review-form" method="POST"><?php echo craftcrawl_csrf_input();?><input type="hidden" name="location_id" value="<?php echo $l['id'];?>"><textarea name="admin_notes" placeholder="Admin notes"><?php echo craftcrawl_admin_escape(($l['adminNotes']??'')!==''?$l['adminNotes']:($l['suggestion_user_notes']??''));?></textarea><div class="admin-readiness-actions"><button name="form_action" value="save_location_notes">Save notes</button><a href="location_hours.php?id=<?php echo $l['id'];?>">Edit hours</a><button name="form_action" value="enable_checkins" <?php echo $has_verified_hours?'':'disabled';?>>Enable check-ins</button><button name="form_action" value="hide_location">Hide location</button></div><?php if(!$has_verified_hours):?><p class="form-help">Verified hours are required before check-ins can be enabled.</p><?php endif;?></form></article><?php endwhile;?></section>
<section class="admin-panel"><h2>Rejected / Hidden Locations &amp; Suggestions</h2><?php while($l=$rejected_hidden->fetch_assoc()):$full_address=trim(implode(', ',array_filter([$l['street_address'], $l['apt_suite'], $l['city'], $l['state'], $l['zip']])));$is_suggestion=$l['recovery_type']==='suggestion';?><article class="admin-list-item admin-recovery-review-item"><div class="admin-recovery-details"><h3><?php echo craftcrawl_admin_escape($l['name']);?></h3><p><?php echo craftcrawl_admin_escape(craftcrawl_admin_business_type_label($l['location_type']));?> · <?php echo craftcrawl_admin_escape($is_suggestion ? 'Suggestion '.ucwords($l['review_status']) : ucwords($l['review_status']));?></p><p><strong>Address:</strong> <?php echo craftcrawl_admin_escape($full_address);?></p><?php if($is_suggestion&&!empty($l['suggested_by'])):?><p><strong>Suggested by:</strong> <?php echo craftcrawl_admin_escape($l['suggested_by']);?></p><?php endif;?><?php if($is_suggestion&&!empty($l['user_notes'])):?><p><strong>User notes:</strong> <?php echo nl2br(craftcrawl_admin_escape($l['user_notes']));?></p><?php endif;?><?php if($is_suggestion&&!empty($l['mapbox_place_id'])):?><p><strong>Mapbox ID:</strong> <?php echo craftcrawl_admin_escape($l['mapbox_place_id']);?></p><?php endif;?><?php if($is_suggestion&&!empty($l['matched_location_id'])):?><p><strong>Matched location:</strong> #<?php echo craftcrawl_admin_escape($l['matched_location_id']);?></p><?php endif;?></div><form class="admin-recovery-review-form" method="POST"><?php echo craftcrawl_csrf_input();?><?php if($is_suggestion):?><input type="hidden" name="suggestion_id" value="<?php echo $l['suggestion_id'];?>"><?php else:?><input type="hidden" name="location_id" value="<?php echo $l['location_id'];?>"><?php endif;?><textarea name="admin_notes" placeholder="Admin notes"><?php echo craftcrawl_admin_escape($l['adminNotes']??'');?></textarea><div class="admin-recovery-review-actions"><?php if($is_suggestion):?><button name="form_action" value="save_suggestion_notes">Save notes</button><button name="form_action" value="restore_suggestion">Move back to pending</button><?php else:?><button name="form_action" value="save_location_notes">Save notes</button><?php if($l['review_status']==='hidden'):?><button name="form_action" value="unhide_location">Restore as unclaimed</button><?php else:?><button name="form_action" value="hide_location">Hide</button><?php endif;?><?php endif;?></div></form></article><?php endwhile;?></section>
</main></div>
<?php include __DIR__ . '/mobile_nav.php'; ?>
<script src="../js/mobile_actions_menu.js?v=<?php echo filemtime(__DIR__ . '/../js/mobile_actions_menu.js'); ?>"></script>
<script src="../js/depth_animations.js?v=<?php echo filemtime(__DIR__ . '/../js/depth_animations.js'); ?>"></script>
<script>window.CraftCrawlAreaShellConfig = { area: 'admin', home: 'dashboard.php', routes: ['dashboard.php','accounts.php','reviews.php','content.php','account_details.php','review_center.php','location_hours.php','import_locations.php'], active: { 'dashboard.php':'dashboard', 'accounts.php':'accounts', 'account_details.php':'accounts', 'reviews.php':'reviews', 'content.php':'content', 'review_center.php':'dashboard', 'location_hours.php':'dashboard', 'import_locations.php':'dashboard' } };</script>
<script src="../js/area_shell_navigation.js?v=<?php echo filemtime(__DIR__ . '/../js/area_shell_navigation.js'); ?>"></script>
</body></html>
